### PR TITLE
General QA, Cleanup and Type Inference Improvements

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

- Add Psalm
- Upgrade coding standard to 3.x
- Fix docs workflow
- setup renovate
- drop the auto-closer
- minor tweaks to dot files and tool config
- Squash a tonne of psalm issues and baseline the rest

### CODE REVIEW

**Comment by gsteel** [comment]
The BC breaks are due to `ExceptionInterface` inheriting from `Throwable` which is really more of a bug fix!

**Comment by froschdesign** [comment]
> The BC breaks are due to `ExceptionInterface` inheriting from `Throwable` which is really more of a bug fix!

Would you still like to release it?

**Comment by gsteel** [comment]
> Would you still like to release it?

Well, we're not abandoning it now, so we might as well clean things up a bit!

**Comment by froschdesign** [comment]
I mean the BC breaks.

**Comment by gsteel** [comment]
Oh yeah. I've released loads of minors with this change. It's only a technical bc break. It won't break anyone's project 👍

**Review by froschdesign — APPROVED** [review]
Go for it! 👍🏻

**Pull request merged**
