### PR TITLE
Allow installation on PHP 8.2

### PR DESCRIPTION
**Pull request by localheinz**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This pull request

- [x] allows installation on PHP 8.2

Blocked by #13.
Blocked by #15.
Blocked by #12.

### CODE REVIEW

**Comment by froschdesign** [comment]
@localheinz 
I have rerun all the jobs, please check the new results.
Thanks in advance! 👍🏻

**Comment by localheinz** [comment]
I will open small pull requests to move forward here, @froschdesign!

**Comment by localheinz** [comment]
@froschdesign @geerteltink @Ocramius 

Passing now, but quite a number of unrelated changes.

If I look at the builds in the other pull requests, looks like current `2.10.x` is also failing.

**Review by Ocramius — APPROVED** [review]
Thanks @localheinz! Yes, indeed unrelated changes, but we're indeed trying to go green-to-green (as much as possible), as it is just going to be forgotten otherwise, sorry

**Comment by localheinz** [comment]
Thank you, @froschdesign and @Ocramius!

**Pull request merged**
